### PR TITLE
Add experimental support for instance mode 

### PR DESCRIPTION
**Pull request by Vindaar**
After my brain was refreshed from exercising I decided to take a stab at implementing this. 

I'm pretty happy with the results! We add a type for a `P5Instance` which contains all symbols that are accessible from the `instance` macro. For each procedure that is to be callable, we generate them from the existing wrapper by using a new `globalAndLocal` macro that takes definitions and outputs two versions of them:
- regular
- one taking a `P5Instance` as first argument, that is to be emitted to JS as `p5Inst.<name>(<args>)` (this is important, as the procedures are methods of the instance, as far as I understand so far)

The new `instance` template shadows the existing sugar templates with versions that generate a new closure and add it to the corresponding field of the `P5Instance` object (remaining templates need to be added as wrapper templates as well as as fields to the `P5Instance` type definition).
Within these templates the body is checked for possible replacements from two sources:
- all procedures that were wrapped in `globalAndLocal` (for `nnkCall` nodes { `nnkDotExpr` will be added later } )
- all fields of the `P5Instance` type (for `nnkSym` / `nnkIdent` nodes)

This approach (that internally uses `CacheSeqs` to store the symbols) has the advantage that we don't convert too little / too many things.

See the example for what the resulting code looks like.

### CODE REVIEW

**Comment by Vindaar** [comment]
@pietroppeter I noticed you're not watching your own repository, so I guess it's possible you'll overlook this.

**Comment by pietroppeter** [comment]
> @pietroppeter I noticed you're not watching your own repository, so I guess it's possible you'll overlook this. 

Ah wow, indeed I got the notification only when you mentioned me. Now I should be watching it. Thanks so much for this! Need to look at it and give you feedback (~~first feedback is probably I will keep instance related code in a separate module instead of the module with the original bindings;~~ **edit**: looked quickly at the implementation and it is evident why it needs to be in the bindings: we need to generate the two versions for global and instance mode).

**Comment by Vindaar** [comment]
The majority of the logic can be moved to a submodule though! I just put it there for convenience at the moment. And given that we use a `CacheSeq` for storing the CT information, it would be safe even to have the define the `globalAndLocal` macro in a submodule (technically using a regular `Table` at CT also works, but that apparently will break incremental compilation once that is a thing).

**Comment by Vindaar** [comment]
Just rebased on current master, moved the instance macro logic to a submodule and extended support for `nnkDotExpr` appearing in the `instance` template bodies.

In principle I consider this ready for merge, with the remaining optional TODOs left:
- [ ] extend the `P5Instance` object to really contain all fields the real instance allows for (I just copied some of the globally defined wrapped variables)
- [ ] make sure to put all procedures that require it under `globalAndLocal`
- [ ] extend the `instance` template to not only include `setup` and `draw`. This also requires an addition to the `P5Instance` class for each addition, as each is stored as a closure in the object. If one decides to provide everything that is `p5sugar.nim` it could also be done with a macro in principle, or just via copy & paste. The code is pretty trivial after all (but I'm not even sure if all of that is valid for `P5Instance`).

**Comment by pietroppeter** [comment]
I will check this out and likely merge it. I want to test it out to have two instances in the same document and possibly create a nimib sugar for those (which includes automatically generated ids for divs). It seems reasonable to have only a partial subset of the functionalities now, we will add them as we go (most of the functionalities in the bindings are still untested for me, since they have no example where they are used).

**Comment by pietroppeter** [comment]
ok, I checked this and tested the two instances. In order for that to work the divName must be a `cstring` and not a `string` (there are multiple occurrences of `string` in the existing bindings, they will likely need to be all changed to `cstring`). I made the changes and update the `instances` example to have two copies of the get started example. works fine!

as another minor changes: used `importjs` instead of `importcpp`.

@vindaar, hope you do not mind I committed directly here, seemed easier. If ok for you I would merge this, close the instance issue and open a new one with the improvements you listed above.

**Comment by pietroppeter** [comment]
ah, another thing I noticed is there was a `import jsffi` left in the examples. I removed it and examples seem to work fine. Is it something that we think might be needed in some cases for instance mode? if so maybe the better way would be to just export it from p5.

**Comment by Vindaar** [comment]
Ah, no. that import is just an accidental left over, because I started writing the prototype code in the example. Thanks for noticing. I'll take it out later.

edit: you can of course also remove it! I don't  mind you committing here at all, no worries!

**Comment by pietroppeter** [comment]
Already removed. Ready to merge on my side.

**Comment by pietroppeter** [comment]
merging, thanks again a lot for this great work @Vindaar !

**Pull request merged**
